// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model/Commander.proto

/*
Package model is a generated protocol buffer package.

It is generated from these files:
	model/Commander.proto

It has these top-level messages:
	UUID
	CommandParams
	Command
	PagedCommands
	Event
	PagedEvents
	PagingInfo
	StreamRequest
*/
package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UUID struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *UUID) Reset()                    { *m = UUID{} }
func (m *UUID) String() string            { return proto.CompactTextString(m) }
func (*UUID) ProtoMessage()               {}
func (*UUID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UUID) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type CommandParams struct {
	Action  string            `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	Data    string            `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	Sync    bool              `protobuf:"varint,3,opt,name=sync" json:"sync,omitempty"`
	Carrier map[string]string `protobuf:"bytes,4,rep,name=carrier" json:"carrier,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *CommandParams) Reset()                    { *m = CommandParams{} }
func (m *CommandParams) String() string            { return proto.CompactTextString(m) }
func (*CommandParams) ProtoMessage()               {}
func (*CommandParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CommandParams) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *CommandParams) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *CommandParams) GetSync() bool {
	if m != nil {
		return m.Sync
	}
	return false
}

func (m *CommandParams) GetCarrier() map[string]string {
	if m != nil {
		return m.Carrier
	}
	return nil
}

type Command struct {
	Id        *UUID             `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Action    string            `protobuf:"bytes,2,opt,name=action" json:"action,omitempty"`
	Data      string            `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	Timestamp int64             `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
	Topic     string            `protobuf:"bytes,5,opt,name=topic" json:"topic,omitempty"`
	Partition int32             `protobuf:"varint,6,opt,name=partition" json:"partition,omitempty"`
	Offset    int64             `protobuf:"varint,7,opt,name=offset" json:"offset,omitempty"`
	Children  []*UUID           `protobuf:"bytes,8,rep,name=children" json:"children,omitempty"`
	Carrier   map[string]string `protobuf:"bytes,9,rep,name=carrier" json:"carrier,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Command) GetId() *UUID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Command) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Command) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Command) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Command) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Command) GetPartition() int32 {
	if m != nil {
		return m.Partition
	}
	return 0
}

func (m *Command) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Command) GetChildren() []*UUID {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *Command) GetCarrier() map[string]string {
	if m != nil {
		return m.Carrier
	}
	return nil
}

type PagedCommands struct {
	Limit    int64      `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	Offset   int64      `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	Total    int64      `protobuf:"varint,3,opt,name=total" json:"total,omitempty"`
	Commands []*Command `protobuf:"bytes,4,rep,name=commands" json:"commands,omitempty"`
}

func (m *PagedCommands) Reset()                    { *m = PagedCommands{} }
func (m *PagedCommands) String() string            { return proto.CompactTextString(m) }
func (*PagedCommands) ProtoMessage()               {}
func (*PagedCommands) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PagedCommands) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *PagedCommands) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *PagedCommands) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PagedCommands) GetCommands() []*Command {
	if m != nil {
		return m.Commands
	}
	return nil
}

type Event struct {
	Id        *UUID             `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Action    string            `protobuf:"bytes,2,opt,name=action" json:"action,omitempty"`
	Data      string            `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	Timestamp int64             `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
	Topic     string            `protobuf:"bytes,5,opt,name=topic" json:"topic,omitempty"`
	Partition int32             `protobuf:"varint,6,opt,name=partition" json:"partition,omitempty"`
	Offset    int64             `protobuf:"varint,7,opt,name=offset" json:"offset,omitempty"`
	Parent    *UUID             `protobuf:"bytes,8,opt,name=parent" json:"parent,omitempty"`
	Carrier   map[string]string `protobuf:"bytes,9,rep,name=carrier" json:"carrier,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Event) GetId() *UUID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Event) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *Event) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *Event) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Event) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Event) GetPartition() int32 {
	if m != nil {
		return m.Partition
	}
	return 0
}

func (m *Event) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Event) GetParent() *UUID {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *Event) GetCarrier() map[string]string {
	if m != nil {
		return m.Carrier
	}
	return nil
}

type PagedEvents struct {
	Limit  int64    `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	Offset int64    `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	Total  int64    `protobuf:"varint,3,opt,name=total" json:"total,omitempty"`
	Events []*Event `protobuf:"bytes,4,rep,name=events" json:"events,omitempty"`
}

func (m *PagedEvents) Reset()                    { *m = PagedEvents{} }
func (m *PagedEvents) String() string            { return proto.CompactTextString(m) }
func (*PagedEvents) ProtoMessage()               {}
func (*PagedEvents) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PagedEvents) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *PagedEvents) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *PagedEvents) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *PagedEvents) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type PagingInfo struct {
	Limit  int64 `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	Offset int64 `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
}

func (m *PagingInfo) Reset()                    { *m = PagingInfo{} }
func (m *PagingInfo) String() string            { return proto.CompactTextString(m) }
func (*PagingInfo) ProtoMessage()               {}
func (*PagingInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *PagingInfo) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *PagingInfo) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type StreamRequest struct {
}

func (m *StreamRequest) Reset()                    { *m = StreamRequest{} }
func (m *StreamRequest) String() string            { return proto.CompactTextString(m) }
func (*StreamRequest) ProtoMessage()               {}
func (*StreamRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func init() {
	proto.RegisterType((*UUID)(nil), "commander.UUID")
	proto.RegisterType((*CommandParams)(nil), "commander.CommandParams")
	proto.RegisterType((*Command)(nil), "commander.Command")
	proto.RegisterType((*PagedCommands)(nil), "commander.PagedCommands")
	proto.RegisterType((*Event)(nil), "commander.Event")
	proto.RegisterType((*PagedEvents)(nil), "commander.PagedEvents")
	proto.RegisterType((*PagingInfo)(nil), "commander.PagingInfo")
	proto.RegisterType((*StreamRequest)(nil), "commander.StreamRequest")
}

func init() { proto.RegisterFile("model/Commander.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 590 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x55, 0xdf, 0x6a, 0xdb, 0x3e,
	0x14, 0x8e, 0xed, 0xfc, 0xf3, 0x49, 0x43, 0x8b, 0xf8, 0xb5, 0x88, 0xd0, 0x1f, 0x0d, 0x82, 0x31,
	0xc3, 0x20, 0x0b, 0xd9, 0x60, 0x5b, 0xa0, 0x94, 0x35, 0xeb, 0x45, 0x60, 0x17, 0x41, 0xa3, 0x37,
	0xbb, 0xd3, 0x6c, 0x25, 0x13, 0x8b, 0xed, 0x4c, 0x56, 0x0b, 0x61, 0x97, 0x7b, 0xa9, 0x3d, 0xc4,
	0x1e, 0x61, 0x97, 0x7b, 0x90, 0x61, 0x59, 0x89, 0xed, 0xc4, 0x61, 0x0c, 0xd6, 0x8b, 0xdd, 0xe9,
	0x1c, 0x7d, 0x47, 0xe7, 0xfb, 0xce, 0x27, 0xcb, 0x70, 0x1a, 0xc6, 0x01, 0x5f, 0x3e, 0x9d, 0xc4,
	0x61, 0xc8, 0xa2, 0x80, 0xcb, 0xc1, 0x4a, 0xc6, 0x2a, 0x46, 0xae, 0xbf, 0x49, 0x90, 0x73, 0xa8,
	0xdf, 0xde, 0x4e, 0xdf, 0xa0, 0xff, 0xa0, 0x71, 0xcf, 0x96, 0x77, 0x1c, 0x5b, 0x7d, 0xcb, 0x73,
	0x69, 0x16, 0x90, 0xef, 0x16, 0x74, 0x4d, 0xf1, 0x8c, 0x49, 0x16, 0x26, 0xe8, 0x0c, 0x9a, 0xcc,
	0x57, 0x22, 0x8e, 0x0c, 0xd0, 0x44, 0x08, 0x41, 0x3d, 0x60, 0x8a, 0x61, 0x5b, 0x67, 0xf5, 0x3a,
	0xcd, 0x25, 0xeb, 0xc8, 0xc7, 0x4e, 0xdf, 0xf2, 0xda, 0x54, 0xaf, 0xd1, 0x15, 0xb4, 0x7c, 0x26,
	0xa5, 0xe0, 0x12, 0xd7, 0xfb, 0x8e, 0xd7, 0x19, 0x3d, 0x1a, 0x6c, 0xc9, 0x0c, 0x4a, 0xad, 0x06,
	0x93, 0x0c, 0x77, 0x13, 0x29, 0xb9, 0xa6, 0x9b, 0xaa, 0xde, 0x18, 0x8e, 0x8a, 0x1b, 0xe8, 0x04,
	0x9c, 0x4f, 0x7c, 0x6d, 0xd8, 0xa4, 0xcb, 0x5c, 0x8a, 0x5d, 0x90, 0x32, 0xb6, 0x5f, 0x5a, 0xe4,
	0xa7, 0x0d, 0x2d, 0xd3, 0x03, 0x5d, 0x80, 0x2d, 0x02, 0x5d, 0xd6, 0x19, 0x1d, 0x17, 0x38, 0xa4,
	0xd3, 0xa0, 0xb6, 0x08, 0x0a, 0x4a, 0xed, 0x4a, 0xa5, 0x4e, 0x41, 0xe9, 0x39, 0xb8, 0x4a, 0x84,
	0x3c, 0x51, 0x2c, 0x5c, 0xe1, 0x7a, 0xdf, 0xf2, 0x1c, 0x9a, 0x27, 0x52, 0x42, 0x2a, 0x5e, 0x09,
	0x1f, 0x37, 0x32, 0x42, 0x3a, 0x48, 0x6b, 0x56, 0x4c, 0x2a, 0xa1, 0x5b, 0x34, 0xfb, 0x96, 0xd7,
	0xa0, 0x79, 0x22, 0xed, 0x1e, 0xcf, 0xe7, 0x09, 0x57, 0xb8, 0xa5, 0x8f, 0x33, 0x11, 0x7a, 0x02,
	0x6d, 0xff, 0xa3, 0x58, 0x06, 0x92, 0x47, 0xb8, 0xad, 0x07, 0xb8, 0x47, 0x7e, 0x0b, 0x40, 0xaf,
	0xf2, 0x61, 0xbb, 0x1a, 0x7b, 0xb1, 0x3f, 0xec, 0x07, 0x18, 0xf3, 0x57, 0x0b, 0xba, 0x33, 0xb6,
	0xe0, 0x81, 0x69, 0x91, 0xa4, 0xd8, 0xa5, 0x08, 0x85, 0xd2, 0xf5, 0x0e, 0xcd, 0x82, 0x82, 0x46,
	0xbb, 0xa4, 0x51, 0xcf, 0x4b, 0xb1, 0xa5, 0x1e, 0xb1, 0x43, 0xb3, 0x00, 0x0d, 0xa0, 0x6d, 0xc8,
	0x27, 0xe6, 0xea, 0xa0, 0x7d, 0x35, 0x74, 0x8b, 0x21, 0x3f, 0x6c, 0x68, 0xdc, 0xdc, 0xf3, 0x48,
	0xfd, 0xab, 0x56, 0x3f, 0x86, 0xe6, 0x8a, 0x49, 0x1e, 0x29, 0xdc, 0xae, 0xa6, 0x6e, 0xb6, 0xd1,
	0x8b, 0x5d, 0x9b, 0xff, 0x2f, 0x20, 0xf5, 0x08, 0x1e, 0xc0, 0xe4, 0x2f, 0xd0, 0xd1, 0x1e, 0xeb,
	0xf3, 0xff, 0x8e, 0xc3, 0x1e, 0x34, 0xb9, 0x3e, 0xcd, 0xf8, 0x7b, 0xb2, 0x2b, 0x83, 0x9a, 0x7d,
	0x32, 0x06, 0x98, 0xb1, 0x85, 0x88, 0x16, 0xd3, 0x68, 0x1e, 0xff, 0x59, 0x6f, 0x72, 0x0c, 0xdd,
	0x77, 0x4a, 0x72, 0x16, 0x52, 0xfe, 0xf9, 0x8e, 0x27, 0x6a, 0xf4, 0xcd, 0x01, 0x77, 0xfb, 0x42,
	0xa2, 0x2b, 0xe8, 0x4e, 0x24, 0x67, 0x8a, 0x6f, 0x1e, 0x0a, 0x7c, 0xe8, 0x81, 0xea, 0x55, 0xdc,
	0x3f, 0x52, 0x43, 0xaf, 0xe1, 0xe8, 0xad, 0x48, 0xd4, 0xf6, 0xee, 0x9f, 0x16, 0x50, 0x39, 0xe9,
	0x1e, 0x2e, 0xa7, 0xf3, 0x8f, 0x85, 0xd4, 0xd0, 0x73, 0xe8, 0x98, 0xe8, 0x7a, 0x3d, 0x0d, 0xd0,
	0xae, 0xf1, 0x07, 0x1b, 0x6f, 0xde, 0xea, 0x4c, 0x5f, 0x89, 0x79, 0x49, 0x72, 0xf5, 0x01, 0x43,
	0x0b, 0x5d, 0x02, 0xa4, 0xdc, 0x8d, 0xa7, 0x07, 0x98, 0x9f, 0xed, 0x32, 0xcf, 0xe0, 0xa4, 0x86,
	0x86, 0xe0, 0xea, 0x75, 0x35, 0xeb, 0x3d, 0x3b, 0x49, 0x0d, 0x5d, 0x42, 0x47, 0x2f, 0x7f, 0xcb,
	0xb8, 0xa2, 0x78, 0x68, 0x5d, 0xb7, 0xde, 0x37, 0xf4, 0x1f, 0xee, 0x43, 0x53, 0xff, 0xd8, 0x9e,
	0xfd, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x04, 0x24, 0xb7, 0x56, 0xf1, 0x06, 0x00, 0x00,
}
