// Code generated by protoc-gen-go.
// source: Commander.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	Commander.proto

It has these top-level messages:
	UUID
	CommandParams
	Command
	PagedCommands
	Event
	PagedEvents
	PagingInfo
	StreamRequest
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import google_protobuf "google/protobuf/struct.pb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal

type UUID struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *UUID) Reset()         { *m = UUID{} }
func (m *UUID) String() string { return proto1.CompactTextString(m) }
func (*UUID) ProtoMessage()    {}

type CommandParams struct {
	Action string                  `protobuf:"bytes,1,opt,name=action" json:"action,omitempty"`
	Data   *google_protobuf.Struct `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	Sync   bool                    `protobuf:"varint,3,opt,name=sync" json:"sync,omitempty"`
}

func (m *CommandParams) Reset()         { *m = CommandParams{} }
func (m *CommandParams) String() string { return proto1.CompactTextString(m) }
func (*CommandParams) ProtoMessage()    {}

func (m *CommandParams) GetData() *google_protobuf.Struct {
	if m != nil {
		return m.Data
	}
	return nil
}

type Command struct {
	Id        *UUID                   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Action    string                  `protobuf:"bytes,2,opt,name=action" json:"action,omitempty"`
	Data      *google_protobuf.Struct `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	Timestamp int64                   `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
	Topic     string                  `protobuf:"bytes,5,opt,name=topic" json:"topic,omitempty"`
	Partition int32                   `protobuf:"varint,6,opt,name=partition" json:"partition,omitempty"`
	Offset    int64                   `protobuf:"varint,7,opt,name=offset" json:"offset,omitempty"`
	Children  []*UUID                 `protobuf:"bytes,8,rep,name=children" json:"children,omitempty"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto1.CompactTextString(m) }
func (*Command) ProtoMessage()    {}

func (m *Command) GetId() *UUID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Command) GetData() *google_protobuf.Struct {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Command) GetChildren() []*UUID {
	if m != nil {
		return m.Children
	}
	return nil
}

type PagedCommands struct {
	Limit    int64      `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	Offset   int64      `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	Total    int64      `protobuf:"varint,3,opt,name=total" json:"total,omitempty"`
	Commands []*Command `protobuf:"bytes,4,rep,name=commands" json:"commands,omitempty"`
}

func (m *PagedCommands) Reset()         { *m = PagedCommands{} }
func (m *PagedCommands) String() string { return proto1.CompactTextString(m) }
func (*PagedCommands) ProtoMessage()    {}

func (m *PagedCommands) GetCommands() []*Command {
	if m != nil {
		return m.Commands
	}
	return nil
}

type Event struct {
	Id        *UUID                   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Action    string                  `protobuf:"bytes,2,opt,name=action" json:"action,omitempty"`
	Data      *google_protobuf.Struct `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	Timestamp int64                   `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
	Topic     string                  `protobuf:"bytes,5,opt,name=topic" json:"topic,omitempty"`
	Partition int32                   `protobuf:"varint,6,opt,name=partition" json:"partition,omitempty"`
	Offset    int64                   `protobuf:"varint,7,opt,name=offset" json:"offset,omitempty"`
	Parent    *UUID                   `protobuf:"bytes,8,opt,name=parent" json:"parent,omitempty"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto1.CompactTextString(m) }
func (*Event) ProtoMessage()    {}

func (m *Event) GetId() *UUID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Event) GetData() *google_protobuf.Struct {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Event) GetParent() *UUID {
	if m != nil {
		return m.Parent
	}
	return nil
}

type PagedEvents struct {
	Limit  int64    `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	Offset int64    `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	Total  int64    `protobuf:"varint,3,opt,name=total" json:"total,omitempty"`
	Events []*Event `protobuf:"bytes,4,rep,name=events" json:"events,omitempty"`
}

func (m *PagedEvents) Reset()         { *m = PagedEvents{} }
func (m *PagedEvents) String() string { return proto1.CompactTextString(m) }
func (*PagedEvents) ProtoMessage()    {}

func (m *PagedEvents) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type PagingInfo struct {
	Limit  int64 `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	Offset int64 `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
}

func (m *PagingInfo) Reset()         { *m = PagingInfo{} }
func (m *PagingInfo) String() string { return proto1.CompactTextString(m) }
func (*PagingInfo) ProtoMessage()    {}

type StreamRequest struct {
}

func (m *StreamRequest) Reset()         { *m = StreamRequest{} }
func (m *StreamRequest) String() string { return proto1.CompactTextString(m) }
func (*StreamRequest) ProtoMessage()    {}

func init() {
}
